const FUNCTIONAL_ADMINISTRATOR = 1;
const OPERATOR = 2;

var allRoles = [FUNCTIONAL_ADMINISTRATOR, OPERATOR];

module.exports = {

    METHOD_GET: ".GET",

    RESOURCES: {
        "/documents.GET": allRoles,
        //"/documents/list.GET": allRoles,
        "/store_operations.GET": allRoles,
        //"/get_store_operations.GET": allRoles,
        "/finance_operations.GET": allRoles,
        "/documents/add.GET": allRoles,
        "/documents/add.POST": allRoles,
        "/documents/edit.GET": allRoles,
        "/documents/edit.POST": allRoles,
        "/contractors.GET": allRoles,
        "/contractors/add.GET": allRoles,
        "/contractors/add.POST": allRoles,
        "/contractors/edit.GET": allRoles,
        "/contractors/edit.POST": allRoles,
        "/products.GET": allRoles,
        "/products/add.GET": allRoles,
        "/products/add.POST": allRoles,
        "/products/edit.GET": allRoles,
        "/products/edit.POST": allRoles,
        "/reports/products_balance.GET": allRoles,
        //"/finances/get_finance_operations.GET": allRoles,
        /*"/delete_users.POST": usersRoles,
        "/create_user_form.GET": usersRoles,
        "/create_user_form.POST": usersRoles,
        "/edit_user_form.GET": usersRoles,
        "/edit_user_form.POST": usersRoles,
        "/devices.GET": devicesRoles,
        "/delete_devices.POST": devicesRoles,
        "/create_device_form.GET": devicesRoles,
        "/create_device_form.POST": devicesRoles,
        "/edit_device_form.GET": devicesRoles,
        "/edit_device_form.POST": devicesRoles,
        "/edit_device_parent.POST": devicesRoles,
        "/create_group_form.GET": devicesRoles,
        "/create_group_form.POST": devicesRoles,
        "/edit_group_form.GET": devicesRoles,
        "/edit_group_form.POST": devicesRoles,
        "/edit_group_parent.POST": devicesRoles,
        "/delete_groups.POST": devicesRoles,
        "/event_setup.GET": eventSetupRoles,
        "/get_event_setup.POST": eventSetupRoles,
        "/set_event_setup.POST": eventSetupRoles,
        "/get_defaults_event_setup.POST": eventSetupRoles,
        "/get_events_setup_template.POST": eventSetupRoles,
        "/delete_events_setup_template.POST": eventSetupRoles,
        "/edit_events_setup_template.POST": eventSetupRoles,
        "/monitoring.GET": monitoringRoles,
        "/fix_events.POST": monitoringRoles,
        "/fix_events_by_device_id.POST": monitoringRoles,
        "/set_device_statuses.POST": monitoringRoles,
        "/get_all_devices_statuses.GET": monitoringRoles,
        "/get_devices_alarm.GET": monitoringRoles,
        "/device/get_state_word.GET": monitoringRoles,
        "/device/execute_device_command.GET": monitoringRoles,
        "/access_control.GET": monitoringRoles,
        "/access_control.POST": monitoringRoles,
        "/http_command.POST": monitoringRoles,
        "/access_log.GET": monitoringRoles,
        "/updates.GET": updatesRoles,
        "/files_uploaded.GET": updatesRoles,
        "/files_uploaded.POST": updatesRoles,
        "/process_files_uploaded.POST": updatesRoles,
        "/process_files_uploaded_all.GET": updatesRoles,
        "/remove_selected_devices_to_uploads.POST": updatesRoles,
        "/action_log.GET": [FUNCTIONAL_ADMINISTRATOR, IT_ADMINISTRATOR],
        "/system_settings.GET": systemSettingsRoles,
        "/edit_system_settings_form.GET": systemSettingsRoles,
        "/edit_system_settings_form.POST": systemSettingsRoles,
        "/key_download.GET": keyDownload,
        "/store_key.POST": keyDownload,
        "/store_key_to_controller.POST": keyDownload,
        "/check_user_alarm.GET": allRoles,
        "/cards_management.GET": cardsRoles,
        "/cards_management/get_card_controller.GET": cardsRoles,
        "/cards_management/get_card_system.GET": cardsRoles,
        "/cards_management/save_cards.POST": cardsRoles,
        "/cards_management/create_cards.POST": cardsRoles,
        "/cards_management/edit_card.POST": cardsRoles,
        "/cards_management/delete_card.DELETE": cardsRoles,
        "/usb_management.GET": usbRoles,
        "/usb_management/create_usb_account.POST": usbRoles,
        "/usb_management/get_usb_accounts.GET": usbRoles,
        "/usb_management/delete_usb_accounts.DELETE": usbRoles,
        "/usb_management/edit_usb_account.POST": usbRoles,
        "/usb_management/save_usb_accounts.POST": usbRoles,
        "/usb_management/get_usb_list.GET": usbRoles*/
    }
};